#!/usr/bin python
# -*- encoding: utf-8 -*-

# for docker run env
EXEC_ENGINE_NAME = "ShangHaiWanGU-A8"
EXEC_ENGINE_IP = "127.0.0.1"   
DPA_ADDRESS = "127.0.0.1"  

ELASTIC_SEARCH = {
    'hosts': ['ELASTIC_SEARCH_ADDR']
}
ENABLE_CELERY_MQ_CLUSTER_SSL = False
CELERY_MQ_CLUSTER = [
    'EXEC_MQ_CLUSTER_ADDR',
]
ENABLE_OTHER_MQ_CLUSTER_SSL = False
OTHER_MQ_CLUSTER = [
    'PUBLIC_MQ_CLUSTER_ADDR',
]

SMART_AGENT_SERVER = {
    'host': 'SMART_AGENT_SERVER_ADDR',
    'port': SMART_AGENT_SERVER_PORT
}

WORKER_EXEC_CONCURRENCY = EXEC_WORKER_CONCURRENCY
WORKER_PREFETCH_MULTIPLIER = 20
WORKER_TASK_TIMEOUT = EXEC_WORKER_TASK_TIMEOUT