FROM centos:7.7.1908
MAINTAINER Zili

# ENV TINI_VERSION v0.19.0
ADD tini /tini

RUN set -ex \
    # 预安装所需组件
    && yum install -y  openssl-devel wget expect  sshpass net-snmp-utils net-tools openssh-clients ipmitool \
    && mkdir /opt/jkexec \
    && chmod +x /tini

WORKDIR /opt/jkexec

COPY venv venv

# 设置环境变量
ENV LD_LIBRARY_PATH /usr/local/lib
ENV EXEC_ENGINE_IP 127.0.0.1
ENV EXEC_ENGINE_NAME ZiliTest
ENV DPA_ADDRESS 127.0.0.1
ENV RABBITMQ_ADDR amqp://admin:admin@127.0.0.1:5672/zone01
ENV ELASTICSEARCH_ADDR http://127.0.0.1:9200
ENV SMART_AGENT_SERVER_PORT 127.0.0.1
ENV SMART_AGENT_SERVER_PORT 13080
ENV EXEC_WORKER_CONCURRENCY 8
ENV EXEC_WORKER_TASK_TIMEOUT 7200

